# Generated by Django 3.2.6 on 2022-04-20 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sub', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('msg', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=122)),
            ],
        ),
        migrations.CreateModel(
            name='login_register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='userform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dob', models.IntegerField()),
                ('gender', models.IntegerField(max_length=100)),
                ('hight', models.IntegerField(max_length=100)),
                ('wbr', models.IntegerField(max_length=100)),
                ('war', models.IntegerField(max_length=100)),
                ('acti', models.IntegerField(max_length=100)),
                ('yav', models.CharField(max_length=100)),
                ('feeling', models.CharField(max_length=100)),
                ('hadache', models.CharField(max_length=100)),
                ('lathrgy', models.CharField(max_length=100)),
                ('reduce', models.CharField(max_length=100)),
                ('wtl', models.CharField(max_length=100)),
                ('dic', models.CharField(max_length=100)),
                ('loi', models.CharField(max_length=100)),
                ('fsleepy', models.CharField(max_length=100)),
                ('bodypain', models.CharField(max_length=100)),
                ('disease', models.CharField(max_length=100)),
                ('usernamenew', models.CharField(max_length=100)),
                ('date', models.DateField(default=8)),
            ],
        ),
    ]
