# Generated by Django 3.2.6 on 2022-04-21 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_userform_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userform',
            name='date',
        ),
    ]
